/* KOL IDS REPORT · UNIFIED ROYAL BLUE + PREMIUM PDF · 20261006 */
(function(){
 const styleId='kol-ids-report-unified-blue-premium-20261006';
 if(document.getElementById(styleId))return;
 const s=document.createElement('style');s.id=styleId;s.textContent=`
  .kol-report-page .report-chart-grid{gap:18px!important}
  .kol-report-page .report-chart-card{background:linear-gradient(180deg,#FFFFFF 0%,#F9FBFF 100%)!important;border:1px solid #D8E2F3!important;border-top:2px solid #2454C7!important;border-radius:16px!important;padding:22px 22px 20px!important;box-shadow:0 12px 34px rgba(36,84,199,.07)!important}
  .kol-report-page .report-chart-head{border-bottom:1px solid #E6ECF6!important;padding-bottom:13px!important;margin-bottom:14px!important}
  .kol-report-page .report-chart-head b{color:#17243C!important;font-size:14px!important;font-weight:800!important;letter-spacing:-.02em!important}
  .kol-report-page .report-chart-head span{color:#667892!important;font-size:10px!important;font-weight:700!important;text-transform:uppercase!important;letter-spacing:.08em!important}
  .kol-report-page .report-chart-svg text{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important}
  .kol-report-page .rchart-value,.kol-report-page .rchart-share{fill:#17243C!important;font-weight:850!important}
  .kol-report-page .rchart-label-strong{fill:#30415D!important;font-weight:750!important}
  .kol-report-page .rchart-label,.kol-report-page .rchart-date-label{fill:#52647F!important;font-weight:650!important}
  .kol-report-page .rchart-axis{fill:#71819A!important;font-weight:650!important}
  .kol-report-page .rchart-legend{fill:#30415D!important;font-weight:750!important}
  .kol-report-page .rchart-gridline{stroke:#E3EAF5!important;stroke-width:1!important}
  .kol-report-page .rchart-bar{fill:#2454C7!important;opacity:1!important}
  .kol-report-page .rchart-bar-track{fill:#E8EEF9!important}
  .kol-report-page .rchart-line-a{stroke:#2454C7!important;stroke-width:3.2!important;stroke-linecap:round!important;stroke-linejoin:round!important}
  .kol-report-page .rchart-line-b{stroke:#6D8DDF!important;stroke-width:3!important;stroke-linecap:round!important;stroke-linejoin:round!important;stroke-dasharray:7 5!important}
  .kol-report-page .rchart-dot-a{fill:#2454C7!important;stroke:#FFFFFF!important;stroke-width:2.5!important}
  .kol-report-page .rchart-dot-b{fill:#6D8DDF!important;stroke:#FFFFFF!important;stroke-width:2.5!important}
  .kol-report-page .rchart-point-value{fill:#17243C!important;font-size:13px!important;font-weight:900!important}
  .kol-report-page .rchart-dot-a-text,.kol-report-page .rchart-dot-b-text{fill:#17243C!important}
  .kol-report-page .report-chart-empty{height:230px!important;min-height:230px!important;border:1px dashed #C9D6EB!important;background:#F8FAFE!important;color:#536783!important;font-weight:750!important}
  .kol-report-page .report-donut-wrap{min-height:250px!important;gap:42px!important}
  .kol-report-page .report-donut{width:174px!important;height:174px!important;flex-basis:174px!important;box-shadow:0 0 0 1px #D5E0F4,0 16px 38px rgba(36,84,199,.09)!important}
  .kol-report-page .report-donut>div{width:132px!important;height:132px!important;background:#FFFFFF!important;box-shadow:0 8px 26px rgba(36,84,199,.08)!important}
  .kol-report-page .report-donut strong{color:#17243C!important;font-size:27px!important;font-weight:900!important}
  .kol-report-page .report-donut span{color:#71819A!important;font-size:8px!important;font-weight:800!important;letter-spacing:.12em!important}
  .kol-report-page .report-legend{gap:13px!important;min-width:190px!important}
  .kol-report-page .report-legend>div{font-size:11px!important;grid-template-columns:9px 1fr auto!important;gap:10px!important}
  .kol-report-page .report-legend i{width:9px!important;height:9px!important}
  .kol-report-page .report-legend span{color:#52647F!important;font-weight:700!important}
  .kol-report-page .report-legend b{color:#2454C7!important;font-size:12px!important;font-weight:900!important}
  .kol-report-page .evidence-status.is-present{border-color:#D5E0F4!important;background:#F7F9FD!important}
  .kol-report-page .evidence-status.is-present b{color:#2454C7!important}
  @media(max-width:900px){.kol-report-page .report-chart-grid{grid-template-columns:1fr!important}}
  @media(max-width:560px){.kol-report-page .report-chart-card{padding:16px!important}.kol-report-page .report-chart-head b{font-size:13px!important}.kol-report-page .rchart-value{font-size:11px!important}.kol-report-page .rchart-label,.kol-report-page .rchart-label-strong{font-size:10px!important}.kol-report-page .rchart-axis{font-size:9px!important}}
 `;document.head.appendChild(s);
})();

function pdfBlueHeader(doc,title,subtitle=''){
 const W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight();
 const header=()=>{doc.setDrawColor(36,84,199);doc.setLineWidth(.65);doc.line(14,12,W-14,12);doc.setFillColor(36,84,199);doc.roundedRect(14,6.2,4.2,4.2,1,1,'F');doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.setTextColor(36,84,199);doc.text('KOL IDS™',21,9.3);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setTextColor(93,108,132);doc.text('INVESTMENT DECISION INTELLIGENCE',W-14,9.3,{align:'right'});};
 const footer=()=>{doc.setDrawColor(220,227,239);doc.setLineWidth(.18);doc.line(14,H-13,W-14,H-13);doc.setFont('helvetica','normal');doc.setFontSize(6.8);doc.setTextColor(105,119,142);doc.text('Confidential · Evidence-led decision report · Observed data only',14,H-8);doc.setTextColor(36,84,199);doc.text('Page '+doc.internal.getNumberOfPages(),W-14,H-8,{align:'right'});};
 header();footer();doc.setFont('helvetica','bold');doc.setFontSize(21);doc.setTextColor(23,36,60);doc.text(pdfSafeText(title),14,25);if(subtitle){doc.setFont('helvetica','normal');doc.setFontSize(8.3);doc.setTextColor(82,100,127);doc.text(pdfSafeText(subtitle),14,31)}return {W,H,header,footer};
}
function pdfBlueSection(doc,ctx,title,kicker=''){pdfPageBreak(doc,ctx,19);ctx.y+=4;doc.setFont('helvetica','bold');doc.setFontSize(6.8);doc.setTextColor(36,84,199);doc.text(pdfSafeText(kicker||'SECTION').toUpperCase(),14,ctx.y);ctx.y+=6;doc.setFontSize(12.5);doc.setTextColor(23,36,60);doc.text(pdfSafeText(title),14,ctx.y);ctx.y+=5;doc.setDrawColor(36,84,199);doc.setLineWidth(.45);doc.line(14,ctx.y,ctx.W-14,ctx.y);ctx.y+=6;}
function pdfBlueMetrics(doc,ctx,items){const gap=4,w=(ctx.W-28-gap*3)/4,h=22;let x=14;items.forEach((it,i)=>{if(i&&i%4===0){ctx.y+=h+4;x=14}if(pdfPageBreak(doc,ctx,h+2))x=14;doc.setFillColor(248,250,254);doc.setDrawColor(214,224,241);doc.roundedRect(x,ctx.y,w,h,2.5,2.5,'FD');doc.setFont('helvetica','bold');doc.setFontSize(6.7);doc.setTextColor(91,109,137);doc.text(String(it.label||'').toUpperCase(),x+4,ctx.y+6.5);doc.setFontSize(11.5);doc.setTextColor(23,36,60);doc.text(pdfSafeText(it.value),x+4,ctx.y+15);x+=w+gap});ctx.y+=h+7}
function pdfChartSvgStyled(svg){if(!svg||!svg.startsWith('<svg'))return svg;const css='.rchart-gridline{stroke:#E3EAF5;stroke-width:1}.rchart-axis{font-family:"Noto Sans Thai",Arial,sans-serif;font-size:13px;fill:#71819A;font-weight:600}.rchart-label{font-family:"Noto Sans Thai",Arial,sans-serif;font-size:13px;fill:#52647F;font-weight:650}.rchart-label-strong{font-family:"Noto Sans Thai",Arial,sans-serif;font-size:15px;fill:#30415D;font-weight:750}.rchart-value{font-family:"Noto Sans Thai",Arial,sans-serif;font-size:16px;fill:#17243C;font-weight:850}.rchart-share{font-family:"Noto Sans Thai",Arial,sans-serif;font-size:15px;fill:#17243C;font-weight:850}.rchart-line-a{stroke:#2454C7;stroke-width:3.2;fill:none;stroke-linecap:round;stroke-linejoin:round}.rchart-line-b{stroke:#6D8DDF;stroke-width:3;fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:7 5}.rchart-dot-a{fill:#2454C7;stroke:#fff;stroke-width:2.5}.rchart-dot-b{fill:#6D8DDF;stroke:#fff;stroke-width:2.5}.rchart-point-value{font-family:"Noto Sans Thai",Arial,sans-serif;font-size:13px;fill:#17243C;font-weight:900}.rchart-legend{font-family:"Noto Sans Thai",Arial,sans-serif;font-size:13px;fill:#30415D;font-weight:750}.rchart-bar{fill:#2454C7}.rchart-bar-track{fill:#E8EEF9}';return svg.replace(/(<svg\b[^>]*>)/,'$1<style>'+css+'</style>')}
function pdfDonutSvg(parts){const valid=(parts||[]).filter(x=>Number(x.value)>0),total=valid.reduce((a,x)=>a+Number(x.value),0);if(!total)return '';const colors=['#2454C7','#4B73D5','#6D8DDF','#91A9E9','#B4C4F2','#D7E0FA'];const cx=190,cy=150,r=88,inner=57;let angle=-Math.PI/2,paths='';valid.forEach((x,i)=>{const a0=angle,a1=angle+(Number(x.value)/total)*Math.PI*2;const x0=cx+r*Math.cos(a0),y0=cy+r*Math.sin(a0),x1=cx+r*Math.cos(a1),y1=cy+r*Math.sin(a1),ix1=cx+inner*Math.cos(a1),iy1=cy+inner*Math.sin(a1),ix0=cx+inner*Math.cos(a0),iy0=cy+inner*Math.sin(a0),large=a1-a0>Math.PI?1:0;paths+='<path d="M '+x0+' '+y0+' A '+r+' '+r+' 0 '+large+' 1 '+x1+' '+y1+' L '+ix1+' '+iy1+' A '+inner+' '+inner+' 0 '+large+' 0 '+ix0+' '+iy0+' Z" fill="'+colors[i%colors.length]+'"/>';angle=a1});const legend=valid.map((x,i)=>{const y=70+i*34;return '<circle cx="330" cy="'+y+'" r="5" fill="'+colors[i%colors.length]+'"/><text x="344" y="'+(y+4)+'" font-family="Noto Sans Thai, Arial" font-size="13" fill="#52647F" font-weight="700">'+esc(x.label)+'</text><text x="500" y="'+(y+4)+'" text-anchor="end" font-family="Noto Sans Thai, Arial" font-size="13" fill="#2454C7" font-weight="900">'+Number(x.value).toLocaleString()+'</text>'}).join('');return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 520 300" width="1040" height="600"><rect width="520" height="300" fill="#FFFFFF"/><circle cx="'+cx+'" cy="'+cy+'" r="'+(r+1)+'" fill="none" stroke="#D5E0F4"/><g>'+paths+'</g><circle cx="'+cx+'" cy="'+cy+'" r="'+inner+'" fill="#FFFFFF"/><text x="'+cx+'" y="'+(cy-2)+'" text-anchor="middle" font-family="Noto Sans Thai, Arial" font-size="30" fill="#17243C" font-weight="900">'+total.toLocaleString()+'</text><text x="'+cx+'" y="'+(cy+17)+'" text-anchor="middle" font-family="Noto Sans Thai, Arial" font-size="10" fill="#71819A" font-weight="800" letter-spacing="2">RECORDS</text>'+legend+'</svg>'}
function pdfChartTitle(doc,ctx,title,note){pdfPageBreak(doc,ctx,30);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(23,36,60);doc.text(pdfSafeText(title),14,ctx.y);ctx.y+=5;doc.setFont('helvetica','normal');doc.setFontSize(7.3);doc.setTextColor(91,109,137);doc.text(pdfSafeText(note),14,ctx.y);ctx.y+=5;}
function pdfAddSvgImage(doc,svg,x,y,w,h){return new Promise(resolve=>{if(!svg||!svg.startsWith('<svg')){resolve(false);return}const img=new Image();img.onload=()=>{try{const scale=2,canvas=document.createElement('canvas');canvas.width=Math.round(w*3.78*scale);canvas.height=Math.round(h*3.78*scale);const c=canvas.getContext('2d');c.fillStyle='#FFFFFF';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(img,0,0,canvas.width,canvas.height);doc.addImage(canvas.toDataURL('image/png',1),'PNG',x,y,w,h,undefined,'FAST');resolve(true)}catch(e){resolve(false)}};img.onerror=()=>resolve(false);img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(pdfChartSvgStyled(svg))})}
function pdfObservationRows(snap){return (snap.perf||[]).map(x=>{const m=x.metadata||{},t=String(m.channelType||'PERFORMANCE').toUpperCase(),sp=num(x.spend_thb),rev=m.netSales!=null?num(m.netSales):num(x.revenue_thb),roas=sp>0&&rev!=null?rev/sp:null,roi=sp>0&&rev!=null?(rev-sp)/sp*100:null;return [S.creators.find(c=>String(c.id)===String(x.creator_id))?.name||'Creator',t,x.observed_at||'—',m.platform||'—',m.evidenceConfidence||x.source||'—',x.actual_score==null?'Pending':`${Math.round(x.actual_score)}/100`,sp==null?'—':pdfFmt(sp,'THB'),rev==null?'—':pdfFmt(rev,'THB'),roas==null?'—':pdfFmt(roas,'x'),roi==null?'—':pdfFmt(roi,'%')]})}
function pdfCreatorDetailRows(snap){return (snap.decisionRows||[]).map(({creator:r,decision:d})=>{const e=d.evidence||{};return [r.name,r.payload?.channel||'—',r.payload?.followers==null?'—':Number(r.payload.followers).toLocaleString(),r.payload?.engagementRate==null?'—':`${Number(r.payload.engagementRate).toFixed(2)}%`,d.decision||'—',d.score==null?'—':Math.round(d.score),Math.round(e.confidence??0),Math.round(e.audienceFit??50),Math.round(e.contentFit??50),Math.round(e.brandFit??50),Math.round(e.performance??0),Math.round(e.commercial??50),Math.round(e.risk??50)]})}

async function buildPremiumFullPDF(){
 if(!window.jspdf?.jsPDF){window.print();return}
 const snap=reportLiveSnapshot(),{p,perf,digital,ecommerce,offline,decisionRows,impact,learning}=snap;const visuals=buildReportVisuals(snap);const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4'});const ctx=pdfBlueHeader(doc,'KOL IDS™ Campaign Intelligence Report','Premium decision pack · observed evidence · creator intelligence · performance · business impact');ctx.y=40;
 pdfBlueMetrics(doc,ctx,[{label:'Creators approved',value:decisionRows.length},{label:'Evidence records',value:perf.length},{label:'Revenue',value:impact.revenue==null?'Not recorded':pdfFmt(impact.revenue,'THB')},{label:'ROAS',value:impact.roas==null?'Not calculable':pdfFmt(impact.roas,'x')}]);
 pdfBlueSection(doc,ctx,'Executive decision summary','01 · executive view');pdfNarrative(doc,ctx,'Decision posture',reportDecisionSignal(snap).action||'Review the linked evidence before changing investment allocation.');pdfNarrative(doc,ctx,'Campaign objective',(p.objectives||[]).join(' · ')||p.objective||p.goal||'Not recorded');pdfNarrative(doc,ctx,'Evidence posture',`${perf.length} observed performance record(s), ${decisionRows.length} creator decision record(s), ${digital.length} digital, ${ecommerce.length} e-commerce and ${offline.length} offline/event record(s).`);
 pdfBlueSection(doc,ctx,'Campaign & audience intelligence','02 · strategic context');pdfRows(doc,ctx,['Field','Observed value'],[['Campaign',S.selectedCampaign?.name||'—'],['Status',S.selectedCampaign?.status||'—'],['Objective',(p.objectives||[]).join(' · ')||p.objective||p.goal||'—'],['Performance model',p.performanceType||'—'],['Budget',pdfFmt(p.budget,'THB')],['Market',p.market||'—'],['Start date',p.startDate||'—'],['End date',p.endDate||'—'],['Brand personality',(p.brandPersonalities||[]).join(' · ')||'—'],['Audience type',S.selectedAudience?.payload?.audienceType||'—'],['Audience persona',S.selectedAudience?.payload?.audiencePersona||'—'],['Audience notes',S.selectedAudience?.payload?.notes||'—']],[55,125]);
 pdfBlueSection(doc,ctx,'Creator decision register','03 · creator intelligence');if(decisionRows.length)pdfRows(doc,ctx,['Creator','Channel','Followers','ER','Decision','Fit','Conf.','Audience','Content','Brand','Perf.','Commercial','Risk'],pdfCreatorDetailRows(snap),[27,17,18,14,20,12,12,13,13,13,13,14,11]);else pdfNarrative(doc,ctx,'Status','No creator decision records are linked to this campaign.');
 decisionRows.slice(0,20).forEach(({creator:r,decision:d})=>{const e=d.evidence||{};pdfNarrative(doc,ctx,r.name,`${d.decision||'—'} · Fit ${d.score==null?'—':Math.round(d.score)}/100 · Confidence ${Math.round(e.confidence??0)}/100 · ${e.reason||e.method||creatorAdaptation(e)||'No rationale recorded.'}`)});
 pdfBlueSection(doc,ctx,'Performance evidence register','04 · observed records');if(perf.length)pdfRows(doc,ctx,['Creator','Type','Observed','Platform','Confidence','Outcome','Spend','Revenue','ROAS','ROI'],pdfObservationRows(snap),[27,17,18,18,19,17,20,22,16,16]);else pdfNarrative(doc,ctx,'Status','No performance evidence was recorded.');
 pdfBlueSection(doc,ctx,'Digital performance detail','04A · multi-platform evidence');if(digital.length)pdfRows(doc,ctx,['Creator','Platform','Observed','Reach','Impressions','Views','Likes','Comments','Shares','Clicks','Conversions','Engagement'],digital.map(x=>[S.creators.find(c=>String(c.id)===String(x.creator_id))?.name||'Creator',x.metadata?.platform||'—',x.observed_at||'—',x.reach==null?'—':Number(x.reach).toLocaleString(),x.impressions==null?'—':Number(x.impressions).toLocaleString(),x.views==null?'—':Number(x.views).toLocaleString(),x.likes==null?'—':Number(x.likes).toLocaleString(),x.comments==null?'—':Number(x.comments).toLocaleString(),x.shares==null?'—':Number(x.shares).toLocaleString(),x.clicks==null?'—':Number(x.clicks).toLocaleString(),x.conversions==null?'—':Number(x.conversions).toLocaleString(),x.engagement==null?'—':Number(x.engagement).toLocaleString()]),[25,17,18,18,20,18,18,18,18,18,18,20]);else pdfNarrative(doc,ctx,'Status','No digital records.');
 pdfBlueSection(doc,ctx,'E-commerce performance detail','04B · commerce evidence');if(ecommerce.length)pdfRows(doc,ctx,['Creator','Platform','Observed','GMV','Net sales','Orders','Paid orders','Discounts','Refunds','AOV','Commission','New customers'],ecommerce.map(x=>{const m=x.metadata||{};return [S.creators.find(c=>String(c.id)===String(x.creator_id))?.name||'Creator',m.platform||'—',x.observed_at||'—',m.gmv==null?'—':pdfFmt(m.gmv,'THB'),m.netSales==null?'—':pdfFmt(m.netSales,'THB'),m.orders==null?'—':Number(m.orders).toLocaleString(),m.paidOrders==null?'—':Number(m.paidOrders).toLocaleString(),m.discounts==null?'—':pdfFmt(m.discounts,'THB'),m.refunds==null?'—':pdfFmt(m.refunds,'THB'),m.aov==null?'—':pdfFmt(m.aov,'THB'),m.commissionAmount==null?'—':pdfFmt(m.commissionAmount,'THB'),m.newCustomers==null?'—':Number(m.newCustomers).toLocaleString()]}),[25,17,18,22,22,17,19,22,22,20,24,22]);else pdfNarrative(doc,ctx,'Status','No e-commerce records.');
 pdfBlueSection(doc,ctx,'Offline / event performance detail','04C · physical evidence');if(offline.length)pdfRows(doc,ctx,['Creator','Event','Observed','Capacity','Attendance','Leads','QR scans','Demos','Samples','Conversions','Engagement','Revenue'],offline.map(x=>{const m=x.metadata||{};return [S.creators.find(c=>String(c.id)===String(x.creator_id))?.name||'Creator',m.eventType||'—',x.observed_at||'—',m.capacity==null?'—':Number(m.capacity).toLocaleString(),m.attendance==null?'—':Number(m.attendance).toLocaleString(),m.qualifiedLeads==null?'—':Number(m.qualifiedLeads).toLocaleString(),m.qrScans==null?'—':Number(m.qrScans).toLocaleString(),m.demos==null?'—':Number(m.demos).toLocaleString(),m.samples==null?'—':Number(m.samples).toLocaleString(),x.conversions==null?'—':Number(x.conversions).toLocaleString(),m.engagement==null?'—':Number(m.engagement).toLocaleString(),x.revenue_thb==null?'—':pdfFmt(x.revenue_thb,'THB')]}),[25,20,18,19,20,19,18,18,18,19,20,22]);else pdfNarrative(doc,ctx,'Status','No offline/event records.');

 const charts=[['Outcome trend','Revenue vs Spend across observed dates',reportSvgLineChart(visuals.trend,{title:'Observed financial movement',aria:'Revenue and spend over observed dates',width:760,height:390}),760,390],['Creator performance','Observed outcome score by creator',reportSvgBarChart(visuals.bars,{title:'Completed outcome score',aria:'Creator observed outcome scores',width:760,height:390}),760,390],['Revenue contribution','Observed revenue contribution by creator',reportSvgRevenueContribution(visuals.revBars,{title:'Revenue share by creator',aria:'Revenue contribution share by creator',width:760,height:390}),760,390],['Evidence mix','Observed records by evidence type',pdfDonutSvg(visuals.mix),520,300]];
 for(let i=0;i<charts.length;i++){const [title,note,svg,sw,sh]=charts[i];doc.addPage();ctx.header();ctx.footer();ctx.y=24;pdfChartTitle(doc,ctx,title,note);const maxW=ctx.W-28,ratio=sw/sh,w=maxW,h=Math.min(90,maxW/ratio);await pdfAddSvgImage(doc,svg,14,ctx.y,w,h);ctx.y+=h+8;const related=i===0?visuals.trend.map(x=>[x.label,x.a==null?'—':pdfFmt(x.a,'THB'),x.b==null?'—':pdfFmt(x.b,'THB')]):i===1?visuals.bars.map(x=>[x.label,Math.round(x.value)]):i===2?visuals.revBars.map(x=>[x.label,pdfFmt(x.value,'THB')]):visuals.mix.map(x=>[x.label,Number(x.value)]);pdfRows(doc,ctx,i===0?['Observed date','Revenue','Spend']:i===1?['Creator','Observed score']:i===2?['Creator','Revenue']:['Evidence type','Records'],related,i===0?[55,63,64]:[115,67]);}

 pdfBlueSection(doc,ctx,'Business impact & unit economics','06 · observed commercial effect');pdfBlueMetrics(doc,ctx,[{label:'Impact score',value:impact.score==null?'Not scored':`${Math.round(impact.score)}/100`},{label:'Revenue',value:impact.revenue==null?'Not recorded':pdfFmt(impact.revenue,'THB')},{label:'Spend',value:impact.spend==null?'Not recorded':pdfFmt(impact.spend,'THB')},{label:'ROAS',value:impact.roas==null?'Not calculable':pdfFmt(impact.roas,'x')}]);pdfRows(doc,ctx,['Metric','Value','Interpretation'],[['Revenue',impact.revenue==null?'Not recorded':pdfFmt(impact.revenue,'THB'),impact.revenue==null?'Evidence unavailable':'Observed commercial output'],['Spend',impact.spend==null?'Not recorded':pdfFmt(impact.spend,'THB'),impact.spend==null?'Evidence unavailable':'Observed investment base'],['ROAS',impact.roas==null?'Not calculable':pdfFmt(impact.roas,'x'),impact.roas==null?'Requires revenue + spend':'Revenue ÷ spend'],['ROI',impact.roi==null?'Not calculable':pdfFmt(impact.roi,'%'),impact.roi==null?'Requires revenue + spend':'(Revenue − spend) ÷ spend'],['Conversions',impact.conversions==null?'Not recorded':pdfFmt(impact.conversions),'Observed conversion outcome'],['Reach',impact.reach==null?'Not recorded':pdfFmt(impact.reach),'Observed reach'],['Views',impact.views==null?'Not recorded':pdfFmt(impact.views),'Observed views'],['Clicks',impact.clicks==null?'Not recorded':pdfFmt(impact.clicks),'Observed traffic response'],['Engagement',impact.engagement==null?'Not recorded':pdfFmt(impact.engagement),'Observed engagement'],['Event attendance',impact.attendance==null?'Not recorded':pdfFmt(impact.attendance),'Observed attendance'],['Qualified leads',impact.leads==null?'Not recorded':pdfFmt(impact.leads),'Observed qualified leads'],['CTR',impact.ctr==null?'Not calculable':pdfFmt(impact.ctr,'%'),'Clicks ÷ impressions'],['Engagement rate',impact.engagementRate==null?'Not calculable':pdfFmt(impact.engagementRate,'%'),'Engagement ÷ impressions'],['Conversion rate',impact.conversionRate==null?'Not calculable':pdfFmt(impact.conversionRate,'%'),'Conversions ÷ clicks']],[50,55,75]);
 pdfBlueSection(doc,ctx,'Learning & next investment decision','07 · institutional memory');pdfNarrative(doc,ctx,'What worked',learning.worked||'Not recorded yet.');pdfNarrative(doc,ctx,'Friction / what did not work',learning.friction||'Not recorded yet.');pdfNarrative(doc,ctx,'Next hypothesis',learning.hypothesis||'Not recorded yet.');const nid=learning.nextInvestmentDecision||{};if(nid.recommendation)pdfNarrative(doc,ctx,'Next investment decision',`${nid.recommendation} · Confidence ${nid.confidence||'—'} · ${nid.reason||''}`);if(nid.threshold)pdfNarrative(doc,ctx,'Success threshold',nid.threshold);if(nid.historicalBenchmark)pdfNarrative(doc,ctx,'Historical benchmark',`ROAS ${nid.historicalBenchmark} · ${nid.historyCount||0} historical campaign(s)`);(learning.nextActions||[]).forEach((x,n)=>pdfNarrative(doc,ctx,`Next action ${n+1}`,x));
 pdfBlueSection(doc,ctx,'Evidence coverage & governance','08 · data quality');pdfRows(doc,ctx,['Evidence class','Status / count'],[['Digital records',digital.length],['E-commerce records',ecommerce.length],['Offline / event records',offline.length],['Decision records',decisionRows.length],['Revenue evidence',impact.revenue==null?'MISSING':'AVAILABLE'],['Spend evidence',impact.spend==null?'MISSING':'AVAILABLE'],['Conversion evidence',impact.conversions==null?'MISSING':'AVAILABLE'],['Impression evidence',impact.hasImpressionEvidence?'AVAILABLE':'MISSING'],['Click evidence',impact.hasClickEvidence?'AVAILABLE':'MISSING'],['Generated at',new Date().toLocaleString('en-GB',{timeZone:'Asia/Bangkok'})]],[85,95]);pdfNarrative(doc,ctx,'Governance note','Use this report to approve, hold, reallocate or test investment based on observed evidence. KOL IDS does not convert missing evidence into invented values. Forecast-like language should be treated as a hypothesis until supported by observed campaign data.');
 doc.save(pdfSaveName('KOL-IDS_Premium-Campaign-Intelligence',S.selectedCampaign?.name));toast('Premium detailed PDF saved','good');
}
function downloadFullPDF(){if(reportExportIsTrial()){showPaidExportGate();return}buildPremiumFullPDF().catch(err=>{console.error(err);toast('Could not generate the detailed PDF. Please try again.','error')})}
