/** KOL_IDS 1.1.0 — canonical release contract. */
var KOL_IDS_RELEASE_LEGACY_V259 = Object.freeze({VERSION:'LEGACY_METADATA',STATUS:'GROWTH_INTELLIGENCE',RUNTIME:'GOOGLE_APPS_SCRIPT',DATA_MOAT:true,API_GATE:true,IDEMPOTENCY:true,OPERATION_REGISTRY:true});
